# Generated by Django 3.2.9 on 2021-12-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userapp',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.EmailField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
