# Generated by Django 3.2.9 on 2021-12-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuatropatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
