# Generated by Django 3.2.9 on 2021-12-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuatropatas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microchip', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=15)),
                ('picture', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=240)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.vet')),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='userapp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.userapp'),
        ),
        migrations.CreateModel(
            name='PetCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=240)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.pet')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='userapp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.userapp'),
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('userapp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuatropatas.userapp')),
            ],
        ),
    ]
